# Workflow for deploying an ASP.NET Core app to Azure Web App
name: Build and deploy ASP.Net Core app to Azure Web App - FinanceWeb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Check out the code from the repository
      - uses: actions/checkout@v4

      # Set up .NET Core SDK version 9.0
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # Build the solution
      - name: Build with dotnet
        run: dotnet build --configuration Release FinanceMVC.sln
        working-directory: C:/Users/Tyler/OneDrive/Desktop/FinanceMVC/FinanceMVCApp

      # Publish the project
      - name: dotnet publish
        run: dotnet publish --configuration Release --output ./publish FinanceMVC.sln
        working-directory: C:/Users/Tyler/OneDrive/Desktop/FinanceMVC/FinanceMVCApp

      # Upload the published files as artifacts for the deploy job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./FinanceMVCApp/publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      # Download the artifact created in the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      # Log in to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Deploy the app to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FinanceWeb' # Replace with your Azure Web App name
          slot-name: 'Production'
          package: ./FinanceMVCApp/publish # Path to the published output
