name: Build and deploy ASP.Net Core app to Azure Web App - FinanceWeb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Set up .NET
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      # Build the solution
      - name: Build with dotnet
        run: dotnet build FinanceMVCApp/FinanceMVC.sln --configuration Release

      # Publish the solution to a folder
      - name: Publish with dotnet
        run: dotnet publish FinanceMVCApp/FinanceMVC.sln -c Release -o publish_output

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FinanceWeb'
          package: publish_output
