name: Build and deploy ASP.Net Core app to Azure Web App - FinanceWeb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      # Build the solution
      - name: Build with dotnet
        run: dotnet build FinanceMVCApp.sln --configuration Release
        working-directory: FinanceMVC/FinanceMVCApp

      # Publish the project
      - name: Publish with dotnet
        run: dotnet publish FinanceMVCApp.sln --configuration Release --output ${{github.workspace}}/publish
        working-directory: FinanceMVC/FinanceMVCApp

      # Upload the published files
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ${{github.workspace}}/publish

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FinanceWeb'
          slot-name: 'Production'
          package: './publish'
